### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by pipi61** [ashtons/ESPGadgetWebDAV#1]
Hi
I use esp8266 Release 2.6.3
If compile, then too many error:
ESPGadgetWebDAV:81:9: error: 'FSFile' was not declared in this scope
         FSFile entry =  folder.openNextFile();
         ^
ESPGadgetWebDAV:261:7: error: expected unqualified-id before '.' token
     FS.mount();
       ^
ESPGadgetWebDAV:264:11: error: expected unqualified-id before '.' token
         FS.format();
          ^
Thank You

**Comment by ashtons** [comment]
I've patched the code to run with recent versions of the ESP libraries. It should hopefully correct the issues mentioned above.

**Comment by pipi61** [comment]
Thank You
